$filePath = "c:\Users\Edoardo\.gemini\antigravity\scratch\DASHBOARD_BRASIL\index.html"
$content = Get-Content -Path $filePath -Raw -Encoding UTF8

$mapping = @(
    @{ Pattern = '<h2>Accesso Riservato</h2>'; Replacement = '<h2 data-i18n="login.title">Accesso Riservato</h2>' },
    @{ Pattern = '<p style="color: var\(--text-secondary\); margin-bottom: 1.5rem;">Inserisci le tue credenziali per continuare</p>'; Replacement = '<p style="color: var(--text-secondary); margin-bottom: 1.5rem;" data-i18n="login.subtitle">Inserisci le tue credenziali per continuare</p>' },
    @{ Pattern = '<label style="font-weight: 600; color: var\(--text-primary\);">Username \(ID\)</label>'; Replacement = '<label style="font-weight: 600; color: var(--text-primary);" data-i18n="login.username">Username (ID)</label>' },
    @{ Pattern = '<label style="font-weight: 600; color: var\(--text-primary\);">Password</label>'; Replacement = '<label style="font-weight: 600; color: var(--text-primary);" data-i18n="login.password">Password</label>' },
    @{ Pattern = '<div id="login-error" class="status-msg error" style="display: none; margin-top: 1rem; text-align: center;">Credenziali errate</div>'; Replacement = '<div id="login-error" class="status-msg error" style="display: none; margin-top: 1rem; text-align: center;" data-i18n="login.error">Credenziali errate</div>' },
    @{ Pattern = '<button type="submit" class="btn btn-primary" style="width: 100%; margin-top: 1.5rem; justify-content: center;">Accedi</button>'; Replacement = '<button type="submit" class="btn btn-primary" style="width: 100%; margin-top: 1.5rem; justify-content: center;" data-i18n="login.button">Accedi</button>' },
    @{ Pattern = '<span>Dashboard</span>'; Replacement = '<span data-i18n="nav.dashboard">Dashboard</span>' },
    @{ Pattern = '<span>Storico Annuale</span>'; Replacement = '<span data-i18n="nav.yearlyHistory">Storico Annuale</span>' },
    @{ Pattern = '<span>Comparatore</span>'; Replacement = '<span data-i18n="nav.comparator">Comparatore</span>' },
    @{ Pattern = '<span>Analisi Dati</span>'; Replacement = '<span data-i18n="nav.dataAnalysis">Analisi Dati</span>' },
    @{ Pattern = '<span>Analisi per Area</span>'; Replacement = '<span data-i18n="nav.areaAnalysis">Analisi per Area</span>' },
    @{ Pattern = '<span>Dettaglio Dati</span>'; Replacement = '<span data-i18n="nav.dataDetail">Dettaglio Dati</span>' },
    @{ Pattern = '<span>Inserisci Dati</span>'; Replacement = '<span data-i18n="nav.insertData">Inserisci Dati</span>' },
    @{ Pattern = '<span>Importa / Esporta</span>'; Replacement = '<span data-i18n="nav.importExport">Importa / Esporta</span>' },
    @{ Pattern = '<span>Gestione Utenti</span>'; Replacement = '<span data-i18n="nav.userManagement">Gestione Utenti</span>' },
    @{ Pattern = '<span>Logout</span>'; Replacement = '<span data-i18n="nav.logout">Logout</span>' },
    @{ Pattern = '<span class="hamburger-label">MENU</span>'; Replacement = '<span class="hamburger-label" data-i18n="sidebar.menu">MENU</span>' },
    @{ Pattern = '<p style="margin: 0;">Panoramica finanziaria e operativa</p>'; Replacement = '<p style="margin: 0;" data-i18n="header.subtitle">Panoramica finanziaria e operativa</p>' },
    @{ Pattern = '<label style="white-space: nowrap; font-weight: 600;">Filtra Anni:</label>'; Replacement = '<label style="white-space: nowrap; font-weight: 600;" data-i18n="header.filterYears">Filtra Anni:</label>' },
    @{ Pattern = '<button id="restoreYearsBtnTop" class="btn-multi-select" style="margin-top: 0;"><i class="ph ph-arrow-counter-clockwise"></i> Ripristina anni nascosti</button>'; Replacement = '<button id="restoreYearsBtnTop" class="btn-multi-select" style="margin-top: 0;"><i class="ph ph-arrow-counter-clockwise"></i> <span data-i18n="header.restoreYears">Ripristina anni nascosti</span></button>' },
    @{ Pattern = '<button id="toggle-multi-select" class="btn-multi-select" style="margin-top: 0;">Attiva Selezione Multipla</button>'; Replacement = '<button id="toggle-multi-select" class="btn-multi-select" style="margin-top: 0;" data-i18n="header.enableMultiSelect">Attiva Selezione Multipla</button>' },
    @{ Pattern = '<i class="ph ph-printer"></i> Esporta PDF <i class="ph ph-caret-down"></i>'; Replacement = '<i class="ph ph-printer"></i> <span data-i18n="header.exportPdf">Esporta PDF</span> <i class="ph ph-caret-down"></i>' },
    @{ Pattern = '<i class="ph ph-file-pdf"></i> PDF \(Verticale\)'; Replacement = '<i class="ph ph-file-pdf"></i> <span data-i18n="header.pdfPortrait">PDF (Verticale)</span>' },
    @{ Pattern = '<i class="ph ph-file-pdf"></i> PDF \(Orizzontale\)'; Replacement = '<i class="ph ph-file-pdf"></i> <span data-i18n="header.pdfLandscape">PDF (Orizzontale)</span>' },
    @{ Pattern = '<i class="ph ph-crop"></i> Ritaglia Area \(PDF\)'; Replacement = '<i class="ph ph-crop"></i> <span data-i18n="header.pdfCrop">Ritaglia Area (PDF)</span>' },
    @{ Pattern = '<h3>Fatturato Totale \(Net Sales\)</h3>'; Replacement = '<h3 data-i18n="kpi.totalRevenueNet">Fatturato Totale (Net Sales)</h3>' },
    @{ Pattern = '<h3>Ricavi Diarias</h3>'; Replacement = '<h3 data-i18n="kpi.revenueDiarias">Ricavi Diarias</h3>' },
    @{ Pattern = '<h3>Occupazione Media</h3>'; Replacement = '<h3 data-i18n="kpi.avgOccupancy">Occupazione Media</h3>' },
    @{ Pattern = '<h3>Fatturato Totale \(Gross\)</h3>'; Replacement = '<h3 data-i18n="kpi.totalRevenueGross">Fatturato Totale (Gross)</h3>' },
    @{ Pattern = '<h3 id="monthlyChartTitle">Andamento Mensile Fatturato</h3>'; Replacement = '<h3 id="monthlyChartTitle" data-i18n="chart.monthlyRevenue">Andamento Mensile Fatturato</h3>' },
    @{ Pattern = '<h3>Fatturato Ultimi 5 Anni</h3>'; Replacement = '<h3 data-i18n="chart.yearlyRevenue">Fatturato Ultimi 5 Anni</h3>' },
    @{ Pattern = '<h3>Andamento Fatturato Annuo \(NET\)</h3>'; Replacement = '<h3 data-i18n="chart.yearlyTrendNet">Andamento Fatturato Annuo (NET)</h3>' },
    @{ Pattern = '<h3 id="yearlyCompositionChartTitle">Composizione Ricavi</h3>'; Replacement = '<h3 id="yearlyCompositionChartTitle" data-i18n="chart.revenueComposition">Composizione Ricavi</h3>' },
    @{ Pattern = '<option value="bar">Barre</option>'; Replacement = '<option value="bar" data-i18n="selector.bar">Barre</option>' },
    @{ Pattern = '<option value="line">Linea</option>'; Replacement = '<option value="line" data-i18n="selector.line">Linea</option>' },
    @{ Pattern = '<option value="doughnut">Ciambella</option>'; Replacement = '<option value="doughnut" data-i18n="selector.doughnut">Ciambella</option>' },
    @{ Pattern = '<option value="pie">Torta</option>'; Replacement = '<option value="pie" data-i18n="selector.pie">Torta</option>' },
    @{ Pattern = '<option value="polarArea">Area Polare</option>'; Replacement = '<option value="polarArea" data-i18n="selector.polarArea">Area Polare</option>' },
    @{ Pattern = '<h2>Storico Annuale</h2>'; Replacement = '<h2 data-i18n="nav.yearlyHistory">Storico Annuale</h2>' },
    @{ Pattern = '<h3>Tabella Aggregata per Anno</h3>'; Replacement = '<h3 data-i18n="nav.yearlyHistory">Tabella Aggregata per Anno</h3>' },
    @{ Pattern = '<th>Anno</th>'; Replacement = '<th data-i18n="table.year">Anno</th>' },
    @{ Pattern = '<th>Diarias</th>'; Replacement = '<th data-i18n="table.diarias">Diarias</th>' },
    @{ Pattern = '<th>A&B</th>'; Replacement = '<th data-i18n="table.fb">A&B</th>' },
    @{ Pattern = '<th>Spa</th>'; Replacement = '<th data-i18n="table.spa">Spa</th>' },
    @{ Pattern = '<th>Outros</th>'; Replacement = '<th data-i18n="table.others">Outros</th>' },
    @{ Pattern = '<th>Net Sales</th>'; Replacement = '<th data-i18n="table.netSales">Net Sales</th>' },
    @{ Pattern = '<th>Taxas</th>'; Replacement = '<th data-i18n="table.taxes">Taxas</th>' },
    @{ Pattern = '<th>Brut Sales</th>'; Replacement = '<th data-i18n="table.grossSales">Brut Sales</th>' },
    @{ Pattern = '<th>Diaria Media</th>'; Replacement = '<th data-i18n="table.avgDiaria">Diaria Media</th>' },
    @{ Pattern = '<th>N\. Diarie</th>'; Replacement = '<th data-i18n="table.numDiarie">N. Diarie</th>' },
    @{ Pattern = '<th>% Occup\.</th>'; Replacement = '<th data-i18n="table.occupancy">% Occup.</th>' },
    @{ Pattern = '<h3 style="margin:0;"><i class="ph ph-scales" style="color: var\(--accent-blue\); margin-right: 8px;"></i> Comparatore Annuale</h3>'; Replacement = '<h3 style="margin:0;"><i class="ph ph-scales" style="color: var(--accent-blue); margin-right: 8px;"></i> <span data-i18n="comparator.title">Comparatore Annuale</span></h3>' },
    @{ Pattern = '<label style="font-weight: 600; font-size: 1.1rem;">Anno 1:</label>'; Replacement = '<label style="font-weight: 600; font-size: 1.1rem;" data-i18n="comparator.year1">Anno 1:</label>' },
    @{ Pattern = '<label style="font-weight: 600; font-size: 1.1rem;">Anno 2:</label>'; Replacement = '<label style="font-weight: 600; font-size: 1.1rem;" data-i18n="comparator.year2">Anno 2:</label>' },
    @{ Pattern = '<th>Mesi</th>'; Replacement = '<th data-i18n="comparator.months">Mesi</th>' },
    @{ Pattern = '<th>Variazione %</th>'; Replacement = '<th data-i18n="comparator.variation">Variazione %</th>' },
    @{ Pattern = '<div style="background-color: #cbd5e1; padding: 0.75rem; text-align: center; font-weight: bold; font-size: 0.9rem; color: #1e293b;">ANNO IN CORSO VS PRECEDENTE \(YTD\)</div>'; Replacement = '<div style="background-color: #cbd5e1; padding: 0.75rem; text-align: center; font-weight: bold; font-size: 0.9rem; color: #1e293b;" data-i18n="comparator.ytd">ANNO IN CORSO VS PRECEDENTE (YTD)</div>' },
    @{ Pattern = '<strong>Info YTD:</strong> La comparazione "Anno in corso vs Precedente" calcola il totale tenendo conto esclusivamente dei mesi in cui sono presenti i dati per l''anno più recente, scartando i mesi successivi dell''anno più vecchio per garantire un confronto a parità di periodo.'; Replacement = '<span data-i18n="comparator.info"><strong>Info YTD:</strong> La comparazione "Anno in corso vs Precedente" calcola il totale tenendo conto esclusivamente dei mesi in cui sono presenti i dati per l''anno più recente, scartando i mesi successivi dell''anno più vecchio per garantire un confronto a parità di periodo.</span>' },
    @{ Pattern = '<h3>Andamento Mensile Comparato</h3>'; Replacement = '<h3 data-i18n="comparator.monthlyTrend">Andamento Mensile Comparato</h3>' },
    @{ Pattern = '<h2 style="margin: 0;">Analisi Dati</h2>'; Replacement = '<h2 style="margin: 0;" data-i18n="nav.dataAnalysis">Analisi Dati</h2>' },
    @{ Pattern = ' Nr\. Diarie'; Replacement = ' <span data-i18n="analysis.numDiarie">Nr. Diarie</span>' },
    @{ Pattern = ' Diaria Media'; Replacement = ' <span data-i18n="analysis.avgDiaria">Diaria Media</span>' },
    @{ Pattern = ' Occupazione %'; Replacement = ' <span data-i18n="analysis.occupancy">Occupazione %</span>' },
    @{ Pattern = '<div style="background-color: var\(--accent-blue\); padding: 0.75rem; text-align: center; font-weight: bold; font-size: 1rem; color: white;" id="analisi-table-title">NR DIARIE</div>'; Replacement = '<div style="background-color: var(--accent-blue); padding: 0.75rem; text-align: center; font-weight: bold; font-size: 1rem; color: white;" id="analisi-table-title" data-i18n="analysis.numDiarie">NR DIARIE</div>' },
    @{ Pattern = '<h3 id="analisi-chart-title">Andamento Annuo</h3>'; Replacement = '<h3 id="analisi-chart-title" data-i18n="analysis.yearlyTrend">Andamento Annuo</h3>' }
)

foreach ($item in $mapping) {
    $content = [regex]::Replace($content, $item.Pattern, $item.Replacement)
}

[System.IO.File]::WriteAllText($filePath, $content, (New-Object System.Text.UTF8Encoding($False)))
Write-Output "Done replacing HTML static strings."
